anguage: node_js
node_js:
  - "9"
before_script:
  - npm install
script: 
- npm run build
- cp dist/Top-Collegue-Front/index.html dist/Top-Collegue-Front/404.html
deploy:
  local-dir: dist/Top-Collegue-Front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email: false